namespace MsfBlitzOptimiser;

internal static class CharTags
{
    internal static List<string> PriorityOrder = new List<string>() {
        "PowerArmor",
        "Horseman",
        "WeaponX",
        "InfinityWatch",
        "WebWarrior",
        "YoungAvenger",
        "Darkhold",
        "Inhuman",
        "Symbiote",
        "Shadowland",
        "HeroesForHire",
        "Xforce",
        "PymTech",
        "Asgard",
        "SinisterSix",
        "Wakanda",
        "Astonishing",
        "Uncanny",
        "BlackOrder",
        "Brotherhood",
        "GotG",

        "DarkHunter",
        "Supernatural",
        "FantasticFour",
        "XFactor",

        "Hydra",
        "Shield",
        "Avenger",
        "Kree",
        "Ravager",
        "Wave1Avenger",
        "Hand",
        "Aim",

        "Cosmic",
        "City",
        "Bio",
        "Mystic",
        "Global",
        "Skill",
        "Tech",
        "Brawler",
        "Blaster",
        "Controller",
        "Support",
        "Hero",
        "Villain",
        "Protector",
        "Legendary",
        "Minion",
        "Military",
        "Mutant",
        "Marauders",
        "Mercenary",

        "NewWarrior",
        "SpiderVerse",
        "SecretAvenger",
        "Darkhold",
        "Defender",
        "Eternal",
        "Xmen",
    };
}